
server:
    port: 8767
spring:
    application:
        name: springcloud-app-api
    cloud:
        nacos:
            discovery:
                server-addr: http://devops.youhoinfo.com:80
                namespace: 1b146843-219b-475e-8acb-b4adae63fd37
