eureka:
    instance:
        hostname: localhost
        prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:8761/eureka/
feign:
    hystrix:
        enabled: false
logging:
    level:
        io:
            seata: info
mybatis:
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: com.vincent.springcloud.app.seata.order.entity
server:
    port: 8083
spring:
    application:
        name: springcloud-app-seata-order
    cloud:
        alibaba:
            seata:
                tx-service-group: fsp_tx_group
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/seata-order
        username: root
        password: 12345678



