
server:
    port: 8768
spring:
    application:
        name: springcloud-app-feign-client
    cloud:
        nacos:
            discovery:
                #换成自己的server-addr地址
                server-addr: http://127.0.0.1:8848
                #换成自己的namespace
                namespace: 1b146843-219b-475e-8acb-b4adae63fd37
