server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/chaoqianglee/springcloud-appconfig
          searchPaths: config-center
#          username:
#          password:

  application:
     name: springcloud-app-config-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#       eureka cluster mode
#      defaultZone: http://peer1:8000/eureka/,http://peer3:8001/eureka/,http://peer3:8002/eureka/



